name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...

    - name: Build
      if: startsWith(github.ref, 'refs/tags/')
      run: go build -o mngarbot_amd64

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mngarbot_amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
